reference:
  name: "openimages"
  root: "/globalwork/bunne/data/openimages/images"
  pattern: "*.jpg"
  batch_size: 1 

candidates:
  scannetpp:
    root: "/globalwork/bunne/data/scannetpp/data"
    pattern: "**/dslr/undistorted_images/*.JPG"
  hypersim:
    root: "/globalwork/bunne/data/hypersim"
    pattern: "**/cam_*/color/*.jpg"
  gta_sfm:
    root: "/globalwork/bunne/data/GTA-Sfm/data/gta_sfm_clean/train"
    pattern: "**/colmap/dense/0/processed/images/*.png"
  seven_scenes:
    root: "/globalwork/bunne/data/7scenes"
    pattern: "**/seq-*/frame-*.color.png"
    max_frames: 100